project_id = "xuvlzovjhzcslfyzmsnw"

[functions.ai-classify]
verify_jwt = false

[functions.ai-parse-pdf]
verify_jwt = false

[functions.ai-doe-template]
verify_jwt = false

[functions.ai-monthly-report]
verify_jwt = false
